"""Plugin Server — Install pipeline.

When a 3rd-party plugin is installed (via REST, CLI, or the SDK),
this module:

1. Creates the plugin folder at ``plugins/<plugin_id>/``
2. Extracts the source into ``plugins/<plugin_id>/cloned_or_extracted _repo/``
   - From a .zip: extract
   - From a git URL: git clone
   - From a local path: shutil.copytree
3. Writes a default ``adapter.py`` (the user can edit it)
4. Writes a default ``__init__.py`` (which lists the installed
   plugin so the auto-discovery walker can find it)

The user is then expected to **edit ``adapter.py``** to import
their 3rd-party code and produce one or more BaseToolPlugin
instances. The Plugin Server's auto-discovery walker picks up
the plugin on the next reload.

Folder layout produced::

    <plugins_root>/<plugin_id>/
        ├── cloned_or_extracted _repo/    # 3rd-party code (verbatim)
        ├── adapter.py                     # 3rd-party writes this
        └── __init__.py                    # auto-generated; lists the plugin
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

logger = logging.getLogger(__name__)


SourceType = Literal["zip", "git", "local_dir", "pip"]


@dataclass
class InstallResult:
    """Result of an install operation."""

    ok: bool
    plugin_id: str
    plugin_dir: Path
    source_type: SourceType
    message: str = ""
    errors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "ok": self.ok,
            "plugin_id": self.plugin_id,
            "plugin_dir": str(self.plugin_dir),
            "source_type": self.source_type,
            "message": self.message,
            "errors": self.errors,
        }


# ───────────────────────────────────────────────────────────────────
# Source extractors
# ───────────────────────────────────────────────────────────────────


def _extract_zip(zip_path: Path, target_dir: Path) -> tuple[bool, str]:
    """Extract a .zip into target_dir."""
    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            zf.extractall(target_dir)
        return True, f"Extracted {zip_path.name}"
    except zipfile.BadZipFile as e:
        return False, f"Not a valid zip file: {e}"
    except Exception as e:
        return False, f"Zip extraction failed: {e}"


def _clone_git(url: str, target_dir: Path, *, branch: str = "main") -> tuple[bool, str]:
    """git clone into target_dir. Optional branch."""
    try:
        cmd = ["git", "clone", "--depth", "1"]
        if branch:
            cmd += ["-b", branch]
        cmd += [url, str(target_dir)]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,  # 5 min for slow clones
        )
        if result.returncode != 0:
            return False, f"git clone failed: {result.stderr.strip()}"
        return True, f"Cloned {url} (branch={branch})"
    except subprocess.TimeoutExpired:
        return False, "git clone timed out after 300s"
    except FileNotFoundError:
        return False, "git is not installed or not in PATH"
    except Exception as e:
        return False, f"git clone error: {e}"


def _copy_local(src_dir: Path, target_dir: Path) -> tuple[bool, str]:
    """Copy a local directory into target_dir."""
    src_dir = src_dir.resolve()
    if not src_dir.exists() or not src_dir.is_dir():
        return False, f"Source directory does not exist: {src_dir}"
    try:
        shutil.copytree(src_dir, target_dir, dirs_exist_ok=True)
        return True, f"Copied {src_dir}"
    except Exception as e:
        return False, f"Copy failed: {e}"


# ───────────────────────────────────────────────────────────────────
# Adapter / __init__ templates
# ───────────────────────────────────────────────────────────────────

# A starter adapter.py that the user fills in. The 3rd-party
# author replaces the body of `discover()` to wrap their code.

ADAPTER_TEMPLATE = '''\
"""
Adapter for {plugin_id} — auto-generated by the plugin server.

Replace the body of `discover()` with code that imports the
3rd-party code from `./cloned_or_extracted _repo/` and returns
a list of BaseToolPlugin instances.

See app/plugin_server/adapter_base.py for the full protocol.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from common_lib.modules.plugin_sdk.adapter_base import BaseAdapter
from common_lib.modules.plugins.base import BaseToolPlugin
from common_lib.modules.plugins.schemas import PluginMetadata


logger = logging.getLogger(__name__)


# TODO: Import your 3rd-party package here. It's available at
# self.cloned_dir / "your_module.py" because the install pipeline
# extracted the source into the cloned/ subfolder.
# Example:
#   from .cloned_or_extracted _repo.your_module import YourClass


class {class_name}Adapter(BaseAdapter):
    """Adapter that wraps the {plugin_id} 3rd-party code into a BaseToolPlugin."""

    def discover(self) -> list[BaseToolPlugin]:
        """Return one or more BaseToolPlugin instances.

        TODO: Replace this stub with code that:
        1. Imports the 3rd-party package
        2. Constructs a wrapper class that exposes the package's
           methods as @tool-decorated functions
        3. Returns [YourWrapper()]

        See examples in the SDK documentation.
        """
        # === START STUB ===
        metadata = PluginMetadata(
            id="{plugin_id}",
            name="{display_name}",
            version="0.1.0",
            description="TODO: describe this plugin",
            category="{category}",
            author="{author}",
            tags=[],
            dependencies=[],
            required_keys=[],
        )

        class StubPlugin(BaseToolPlugin):
            def __init__(self):
                self.metadata = metadata

            def check_health(self):
                from common_lib.modules.plugins.schemas import (
                    HealthStatus,
                    PluginHealth,
                )
                return PluginHealth(
                    status=HealthStatus.DISCOVERED,
                    message="Stub plugin — replace discover() with real implementation",
                )

            def get_nodes(self):
                return []

            # TODO: add @sdk.tool methods that wrap your 3rd-party code

        return [StubPlugin()]
        # === END STUB ===

    def warm_up(self) -> None:
        """Optional: one-time setup after discovery.

        E.g. open a long-lived client, validate credentials.
        """
        pass

    def dispose(self) -> None:
        """Optional: cleanup before unload.

        E.g. close client connections.
        """
        pass
'''


# __init__.py for an installed plugin. The auto-discovery walker
# imports this module and looks for `PLUGIN_ID` and `ADAPTER_CLASS`.

PLUGIN_INIT_TEMPLATE = '''\
"""Plugin manifest for {plugin_id} — auto-generated.

This file is imported by the plugin server's auto-discovery walker.
The walker looks for `PLUGIN_ID` (must match the folder name) and
`ADAPTER_CLASS` (the adapter class to instantiate).

After installing, edit `adapter.py` to wrap your 3rd-party code.
"""

from __future__ import annotations

# The id of this plugin (must match the folder name)
PLUGIN_ID = "{plugin_id}"

# The adapter class. After editing adapter.py, change this to
# point at your real adapter class. The default is the auto-
# generated stub.
try:
    from .adapter import {class_name}Adapter
    ADAPTER_CLASS = {class_name}Adapter
except ImportError as e:
    ADAPTER_CLASS = None
    import logging
    logging.getLogger(__name__).warning(
        f"Plugin {plugin_id}: failed to import adapter: {{e}}"
    )
'''


def write_starter_adapter(
    plugin_dir: Path,
    plugin_id: str,
    class_name: str,
    *,
    display_name: str = "My Plugin",
    category: str = "general",
    author: str = "Anonymous",
) -> Path:
    """Write a starter adapter.py at plugin_dir/adapter.py.

    If adapter.py already exists, leave it alone (the user has
    already started customising it).
    """
    adapter_path = plugin_dir / "adapter.py"
    if adapter_path.exists():
        logger.info(f"adapter.py already exists at {adapter_path}; leaving alone")
        return adapter_path

    content = ADAPTER_TEMPLATE.format(
        plugin_id=plugin_id,
        class_name=class_name,
        display_name=display_name,
        category=category,
        author=author,
    )
    adapter_path.write_text(content, encoding="utf-8")
    logger.info(f"Wrote starter adapter.py at {adapter_path}")
    return adapter_path


def write_plugin_init(
    plugin_dir: Path,
    plugin_id: str,
    class_name: str,
) -> Path:
    """Write __init__.py at plugin_dir/__init__.py.

    If __init__.py already exists, leave it alone.
    """
    init_path = plugin_dir / "__init__.py"
    if init_path.exists():
        logger.info(f"__init__.py already exists at {init_path}; leaving alone")
        return init_path

    content = PLUGIN_INIT_TEMPLATE.format(
        plugin_id=plugin_id,
        class_name=class_name,
    )
    init_path.write_text(content, encoding="utf-8")
    logger.info(f"Wrote __init__.py at {init_path}")
    return init_path


# ───────────────────────────────────────────────────────────────────
# Main install entry point
# ───────────────────────────────────────────────────────────────────


def _to_class_name(plugin_id: str) -> str:
    """Convert snake_case plugin id to PascalCase + 'Adapter'."""
    parts = plugin_id.replace("-", "_").split("_")
    name = "".join(p.title() for p in parts)
    if not name.endswith("Adapter"):
        name += "Adapter"
    return name


def install_plugin(
    plugin_id: str,
    *,
    source_zip: str | Path | None = None,
    source_git: str | None = None,
    source_branch: str = "main",
    source_local_dir: str | Path | None = None,
    plugins_root: str | Path | None = None,
    overwrite: bool = False,
    display_name: str | None = None,
    category: str = "general",
    author: str = "Anonymous",
) -> InstallResult:
    """Install a 3rd-party plugin from one of three sources.

    Exactly one of ``source_zip``, ``source_git``, ``source_local_dir``
    must be provided.

    Args:
        plugin_id: Stable id (snake_case).
        source_zip: Path to a .zip file to extract.
        source_git: Git URL to clone.
        source_local_dir: Local directory to copy.
        source_branch: Git branch (default 'main').
        plugins_root: Override the default plugins directory.
        overwrite: If True, replace an existing install.
        display_name: Display name for the stub adapter.
        category: Category for the stub adapter.
        author: Author for the stub adapter.

    Returns:
        InstallResult with ok=True on success.
    """
    # Validate exactly one source
    sources = {
        "zip": source_zip is not None,
        "git": source_git is not None,
        "local_dir": source_local_dir is not None,
    }
    provided = [k for k, v in sources.items() if v]
    if len(provided) != 1:
        return InstallResult(
            ok=False,
            plugin_id=plugin_id,
            plugin_dir=Path(),
            source_type="zip",  # placeholder
            errors=[f"Exactly one source required, got {len(provided)}: {provided}"],
        )

    # Validate plugin_id
    if not plugin_id.replace("_", "").replace("-", "").isalnum():
        return InstallResult(
            ok=False,
            plugin_id=plugin_id,
            plugin_dir=Path(),
            source_type="zip",
            errors=["plugin_id must be alphanumeric (with _ or - allowed)"],
        )

    # Resolve root
    if plugins_root is None:
        # Default: <plugin_server>/plugins/
        plugins_root = Path(__file__).parent.parent / "plugins"
    plugins_root = Path(plugins_root)
    plugins_root.mkdir(parents=True, exist_ok=True)

    plugin_dir = plugins_root / plugin_id
    cloned_dir = plugin_dir / "cloned_or_extracted _repo"

    # Check for existing install
    if plugin_dir.exists() and not overwrite:
        return InstallResult(
            ok=False,
            plugin_id=plugin_id,
            plugin_dir=plugin_dir,
            source_type=provided[0],
            errors=[
                f"Plugin '{plugin_id}' already exists at {plugin_dir}. "
                f"Pass overwrite=True to replace."
            ],
        )

    # Remove existing if overwriting
    if plugin_dir.exists() and overwrite:
        shutil.rmtree(plugin_dir, ignore_errors=True)

    # Create folder
    plugin_dir.mkdir(parents=True)
    cloned_dir.mkdir()

    # Extract / clone / copy
    if source_zip is not None:
        ok, msg = _extract_zip(Path(source_zip), cloned_dir)
        source_type: SourceType = "zip"
    elif source_git is not None:
        ok, msg = _clone_git(source_git, cloned_dir, branch=source_branch)
        source_type = "git"
    else:
        ok, msg = _copy_local(Path(source_local_dir), cloned_dir)
        source_type = "local_dir"

    if not ok:
        # Clean up the partial install
        shutil.rmtree(plugin_dir, ignore_errors=True)
        return InstallResult(
            ok=False,
            plugin_id=plugin_id,
            plugin_dir=plugin_dir,
            source_type=source_type,
            errors=[msg],
        )

    # Write starter adapter.py and __init__.py
    class_name = _to_class_name(plugin_id)
    try:
        write_starter_adapter(
            plugin_dir,
            plugin_id,
            class_name,
            display_name=display_name or plugin_id.replace("_", " ").title(),
            category=category,
            author=author,
        )
        write_plugin_init(plugin_dir, plugin_id, class_name)
    except Exception as e:
        shutil.rmtree(plugin_dir, ignore_errors=True)
        return InstallResult(
            ok=False,
            plugin_id=plugin_id,
            plugin_dir=plugin_dir,
            source_type=source_type,
            errors=[f"Failed to write starter files: {e}"],
        )

    logger.info(f"Installed plugin '{plugin_id}' from {source_type} into {plugin_dir}")
    return InstallResult(
        ok=True,
        plugin_id=plugin_id,
        plugin_dir=plugin_dir,
        source_type=source_type,
        message=msg,
    )


def uninstall_plugin(
    plugin_id: str,
    plugins_root: str | Path | None = None,
) -> bool:
    """Remove an installed plugin.

    Returns True if removed, False if not found.
    """
    if plugins_root is None:
        plugins_root = Path(__file__).parent.parent / "plugins"
    plugins_root = Path(plugins_root)
    plugin_dir = plugins_root / plugin_id
    if not plugin_dir.exists():
        return False
    shutil.rmtree(plugin_dir, ignore_errors=True)
    logger.info(f"Uninstalled plugin '{plugin_id}' from {plugin_dir}")
    return True


__all__ = [
    "install_plugin",
    "uninstall_plugin",
    "write_starter_adapter",
    "write_plugin_init",
    "InstallResult",
    "SourceType",
]
