// generateOpenAPISpec.ts

import swaggerJSDoc from 'swagger-jsdoc';
import * as yaml from 'yaml';
import express from 'express';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';
import { writeFileSync } from 'fs';

const app = express();
const PORT = 3000;

const options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'Your API',
            version: '1.0.0',
            description: 'API documentation generated by swagger-jsdoc',
        },
    },
    apis: ['src/routes/*.ts'], // Specify the path to your route files
};

const swaggerSpec = swaggerJSDoc(options);

// Determine the current directory
const currentDir = dirname(fileURLToPath(import.meta.url));

// Save the generated OpenAPI specification to a file
const outputPath = join(currentDir, 'swagger.yaml');
const yamlString = yaml.stringify(swaggerSpec);

// Write YAML string to file
writeFileSync(outputPath, yamlString, 'utf-8');

console.log(`OpenAPI specification has been generated successfully. Output file: ${outputPath}`);
