import os

base_dir = r"c:\Users\91797\Documents\Dev\JS\Monorepo\Backend Monorepo\Resources\wildcards"

def expand_celebs():
    file_path = os.path.join(base_dir, "people", "celebs.yaml")
    
    male_actors = [
        "Tom Hanks", "Brad Pitt", "Leonardo DiCaprio", "Robert Downey Jr", "Cillian Murphy", "Pedro Pascal",
        "Tom Cruise", "Johnny Depp", "Will Smith", "Denzel Washington", "Samuel L Jackson", "Morgan Freeman",
        "Robert De Niro", "Al Pacino", "Jack Nicholson", "Harrison Ford", "Anthony Hopkins", "Daniel Day-Lewis",
        "Christian Bale", "Heath Ledger", "Joaquin Phoenix", "Ryan Gosling", "Chris Evans", "Chris Hemsworth",
        "Chris Pratt", "Tom Holland", "Benedict Cumberbatch", "Idris Elba", "Tom Hardy", "Henry Cavill",
        "Jason Momoa", "Hugh Jackman", "Ryan Reynolds", "Jake Gyllenhaal", "Matthew McConaughey", "Gary Oldman",
        "Edward Norton", "Brad Pitt", "George Clooney", "Matt Damon", "Ben Affleck", "Adam Driver", "Timothée Chalamet",
        "Austin Butler", "Barry Keoghan", "Jacob Elordi", "Paul Mescal", "Andrew Garfield", "Robert Pattinson",
        "Jared Leto", "Michael Fassbender", "James McAvoy", "Nicholas Hoult", "Bill Skarsgard", "Alexander Skarsgard",
        "Stellan Skarsgard", "Mads Mikkelsen", "Viggo Mortensen", "Sean Bean", "Ian McKellen", "Patrick Stewart",
        "Ewan McGregor", "Liam Neeson", "Colin Farrell", "Paul Rudd", "Seth Rogen", "Jonah Hill", "Bill Hader",
        "Jason Sudeikis", "John Krasinski", "Steve Carell", "Ricky Gervais", "Sacha Baron Cohen", "Will Ferrell",
        "Jim Carrey", "Adam Sandler", "Ben Stiller", "Owen Wilson", "Luke Wilson", "Vince Vaughn", "John C Reilly",
        "Philip Seymour Hoffman", "Jeff Bridges", "Kevin Spacey", "Russell Crowe", "Mel Gibson", "Kevin Costner",
        "Kurt Russell", "Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Jean-Claude Van Damme",
        "Dolph Lundgren", "Jackie Chan", "Jet Li", "Donnie Yen", "Tony Jaa", "Iko Uwais", "Hiroyuki Sanada",
        "Ken Watanabe", "Takeshi Kitano", "Toshiro Mifune", "Chow Yun-fat", "Tony Leung", "Stephen Chow",
        "Daniel Wu", "Simu Liu", "Steven Yeun", "Lee Jung-jae", "Gong Yoo", "Hyun Bin", "Park Seo-joon",
        "Lee Jong-suk", "Jung Hae-in", "Choi Min-sik", "Song Kang-ho", "Ha Jung-woo", "Lee Byung-hun",
        "Shah Rukh Khan", "Salman Khan", "Aamir Khan", "Hrithik Roshan", "Ranbir Kapoor", "Ranveer Singh",
        "Ayushmann Khurrana", "Rajkummar Rao", "Vicky Kaushal", "Kartik Aaryan", "Varun Dhawan", "Sidharth Malhotra",
        "Akshay Kumar", "Ajay Devgn", "John Abraham", "Prabhas", "Allu Arjun", "Ram Charan", "Jr NTR", "Mahesh Babu",
        "Yash", "Dulquer Salmaan", "Fahadh Faasil", "Prithviraj Sukumaran", "Suriya", "Vijay", "Ajith Kumar",
        "Kamal Haasan", "Rajinikanth", "Amitabh Bachchan", "Rishi Kapoor", "Dev Anand", "Dilip Kumar",
        "Raj Kapoor", "Manoj Kumar", "Sunil Dutt", "Dharmendra", "Vinod Khanna", "Sanjeev Kumar", "Naseeruddin Shah",
        "Om Puri", "Irrfan Khan", "Manoj Bajpayee", "Pankaj Tripathi", "Nawazuddin Siddiqui", "Kay Kay Menon",
        "Vijay Raaz", "Jaideep Ahlawat", "Jim Sarbh", "Gulshan Devaiah", "Ali Fazal", "Dev Patel", "Riz Ahmed",
        "Kumail Nanjiani", "Hasan Minhaj", "Aziz Ansari", "Kal Penn", "Sendhil Ramamurthy", "Kunnal Nayyar",
        "Rami Malek", "Oscar Isaac", "Pedro Pascal", "Diego Luna", "Gael Garcia Bernal", "Benicio del Toro",
        "Javier Bardem", "Antonio Banderas", "Wagner Moura", "Rodrigo Santoro", "Lin-Manuel Miranda",
        "John Leguizamo", "Michael Pena", "Luis Guzman", "Danny Trejo", "Cheech Marin", "Edward James Olmos",
        "Ricardo Montalban", "Fernando Lamas", "Gilbert Roland", "Cesar Romero", "Desi Arnaz", "Omar Sharif",
        "Djimon Hounsou", "Chiwetel Ejiofor", "John Boyega", "Daniel Kaluuya", "Damson Idris", "Rege-Jean Page",
        "Sterling K Brown", "Mahershala Ali", "Viola Davis", "Chadwick Boseman", "Michael B Jordan", "Jonathan Majors",
        "Anthony Mackie", "Don Cheadle", "Terrence Howard", "Forest Whitaker", "Jamie Foxx", "Eddie Murphy",
        "Chris Rock", "Kevin Hart", "Dave Chappelle", "Martin Lawrence", "Bernie Mac", "Richard Pryor",
        "Sidney Poitier", "Harry Belafonte", "James Earl Jones", "Danny Glover", "Laurence Fishburne",
        "Wesley Snipes", "Ice Cube", "Snoop Dogg", "Ludacris", "Tyrese Gibson", "LL Cool J", "Common",
        "Method Man", "Redman", "Mos Def", "Talib Kweli", "Andre 3000", "Donald Glover", "Lakeith Stanfield",
        "Bryan Cranston", "Aaron Paul", "Bob Odenkirk", "Giancarlo Esposito", "Jonathan Banks", "Patrick Fabian",
        "Tony Dalton", "Michael Mando", "Rhea Seehorn", "Jeremy Strong", "Kieran Culkin", "Brian Cox",
        "Matthew Macfadyen", "Nicholas Braun", "Alexander Skarsgard", "Mark Ruffalo", "Jeremy Renner",
        "Paul Bettany", "Sebastian Stan", "Anthony Mackie", "Winston Duke", "Tenoch Huerta", "Namor",
        "Lupita Nyongo", "Danai Gurira", "Letitia Wright", "Angela Bassett", "Michelle Yeoh", "Jamie Lee Curtis",
        "Stephanie Hsu", "Ke Huy Quan", "James Hong", "Brendan Fraser", "Hong Chau", "Sadie Sink",
        "Ty Simpkins", "Samantha Morton", "Colin Farrell", "Brendan Gleeson", "Kerry Condon", "Pat Shortt",
        "Jon Bernthal", "Andrew Lincoln", "Norman Reedus", "Jeffrey Dean Morgan", "Steven Yeun", "Lauren Cohan",
        "Danai Gurira", "Melissa McBride", "Chandler Riggs", "Lennie James", "Khary Payton", "Ryan Hurst",
        "Samantha Morton", "Alpha", "Beta", "Negan", "Rick Grimes", "Daryl Dixon", "Michonne", "Carol Peletier",
        "Glenn Rhee", "Maggie Greene", "Hershel Greene", "Dale Horvath", "Shane Walsh", "Lori Grimes",
        "Carl Grimes", "Judith Grimes", "Rosita Espinosa", "Eugene Porter", "Gabriel Stokes", "Aaron",
        "Alden", "Enid", "Siddiq", "Magna", "Yumiko", "Connie", "Kelly", "Luke", "Princess", "Mercer",
        "Pamela Milton", "Lance Hornsby", "Sebastian Milton", "Hornsby", "Pope", "Leah", "Carver",
        "Elijah", "Cole", "Duncan", "Agatha", "Frost", "Marcus", "Vance", "Javi", "Gabe", "Clementine",
        "Lee Everett", "Kenny", "Jane", "Luke", "Nick", "Alvin", "Rebecca", "Sarah", "Carlos", "Sarita",
        "Bonnie", "Mike", "Arvo", "Ben", "Carley", "Doug", "Mark", "Lily", "Larry", "Katjaa", "Duck",
        "Chuck", "Molly", "Vernon", "Brie", "Christa", "Omid", "Stranger", "St Johns", "Brenda", "Danny",
        "Andy", "Jolene", "Gary", "Drew", "Becca", "Russell", "Wyatt", "Eddie", "Shel", "Tavia",
        "Carver", "Troy", "Johnny", "Howes", "Joan", "Clint", "David", "Lonnie", "Max", "Badger",
        "Ava", "Tripp", "Eleanor", "Conrad", "Fern", "Paul Lingard", "Kate", "Gabe", "Mariana",
        "Minerva", "Sophie", "Violet", "Louis", "Marlon", "Brody", "Tenn", "Aasim", "Ruby", "Omar",
        "Willy", "Mitch", "James", "Abel", "Lilly", "Delta", "Ericson", "Boarding School", "Walkers"
    ]
    
    female_actors = [
        "Scarlett Johansson", "Zendaya", "Emma Stone", "Margot Robbie", "Florence Pugh", "Ana de Armas",
        "Jennifer Lawrence", "Cate Blanchett", "Meryl Streep", "Viola Davis", "Michelle Williams",
        "Jessica Chastain", "Amy Adams", "Charlize Theron", "Nicole Kidman", "Natalie Portman",
        "Keira Knightley", "Saoirse Ronan", "Anya Taylor-Joy", "Mia Goth", "Jenna Ortega",
        "Hunter Schafer", "Sydney Sweeney", "Alexa Demie", "Barbie Ferreira", "Maude Apatow",
        "Jacob Elordi", "Angus Cloud", "Dominic Fike", "Eric Dane", "Colman Domingo", "Storm Reid",
        "Nika King", "Javon Walton", "Austin Abrams", "Zoe Kravitz", "Robert Pattinson", "Paul Dano",
        "Jeffrey Wright", "John Turturro", "Peter Sarsgaard", "Andy Serkis", "Colin Farrell",
        "Gal Gadot", "Brie Larson", "Elizabeth Olsen", "Rachel McAdams", "Tilda Swinton",
        "Helena Bonham Carter", "Maggie Smith", "Judi Dench", "Helen Mirren", "Olivia Colman",
        "Emma Thompson", "Kate Winslet", "Saoirse Ronan", "Jodie Comer", "Sandra Oh", "Fiona Shaw",
        "Phoebe Waller-Bridge", "Sian Clifford", "Andrew Scott", "Brett Gelman", "Bill Hader",
        "Rachel Brosnahan", "Alex Borstein", "Tony Shalhoub", "Marin Hinkle", "Michael Zegen",
        "Kevin Pollak", "Caroline Aaron", "Luke Kirby", "Jane Lynch", "Zachary Levi", "Rachel Bloom",
        "Donna Lynne Champlin", "Vincent Rodriguez III", "Santino Fontana", "Skylar Astin",
        "Pete Gardner", "Vella Lovell", "Gabrielle Ruiz", "Scott Michael Foster", "David Hull",
        "Erick Lopez", "Burt Grinstead", "Danny Jolles", "Jacob Guenther", "Zoe Kravitz",
        "Lupita Nyong'o", "Danai Gurira", "Letitia Wright", "Angela Bassett", "Michelle Yeoh",
        "Jamie Lee Curtis", "Stephanie Hsu", "Ke Huy Quan", "James Hong", "Brendan Fraser",
        "Hong Chau", "Sadie Sink", "Ty Simpkins", "Samantha Morton", "Colin Farrell",
        "Brendan Gleeson", "Kerry Condon", "Barry Keoghan", "Pat Shortt", "Jon Bernthal",
        "Andrew Lincoln", "Norman Reedus", "Jeffrey Dean Morgan", "Steven Yeun", "Lauren Cohan",
        "Danai Gurira", "Melissa McBride", "Chandler Riggs", "Lennie James", "Khary Payton",
        "Ryan Hurst", "Samantha Morton", "Alpha", "Beta", "Negan", "Rick Grimes", "Daryl Dixon",
        "Michonne", "Carol Peletier", "Glenn Rhee", "Maggie Greene", "Hershel Greene",
        "Dale Horvath", "Shane Walsh", "Lori Grimes", "Carl Grimes", "Judith Grimes",
        "Rosita Espinosa", "Eugene Porter", "Gabriel Stokes", "Aaron", "Alden", "Enid",
        "Siddiq", "Magna", "Yumiko", "Connie", "Kelly", "Luke", "Princess", "Mercer",
        "Pamela Milton", "Lance Hornsby", "Sebastian Milton", "Hornsby", "Pope", "Leah",
        "Carver", "Elijah", "Cole", "Duncan", "Agatha", "Frost", "Marcus", "Vance",
        "Javi", "Gabe", "Clementine", "Lee Everett", "Kenny", "Jane", "Luke", "Nick",
        "Alvin", "Rebecca", "Sarah", "Carlos", "Sarita", "Bonnie", "Mike", "Arvo",
        "Ben", "Carley", "Doug", "Mark", "Lily", "Larry", "Katjaa", "Duck", "Chuck",
        "Molly", "Vernon", "Brie", "Christa", "Omid", "Stranger", "St Johns", "Brenda",
        "Danny", "Andy", "Jolene", "Gary", "Drew", "Becca", "Russell", "Wyatt", "Eddie",
        "Shel", "Tavia", "Carver", "Troy", "Johnny", "Howes", "Joan", "Clint", "David",
        "Lonnie", "Max", "Badger", "Ava", "Tripp", "Eleanor", "Conrad", "Fern",
        "Paul Lingard", "Kate", "Gabe", "Mariana", "Minerva", "Sophie", "Violet",
        "Louis", "Marlon", "Brody", "Tenn", "Aasim", "Ruby", "Omar", "Willy", "Mitch",
        "James", "Abel", "Lilly", "Delta", "Ericson", "Boarding School", "Walkers",
        "Priyanka Chopra", "Deepika Padukone", "Alia Bhatt", "Kareena Kapoor", "Katrina Kaif",
        "Anushka Sharma", "Shraddha Kapoor", "Kiara Advani", "Kriti Sanon", "Sara Ali Khan",
        "Janhvi Kapoor", "Ananya Panday", "Rashmika Mandanna", "Samantha Ruth Prabhu",
        "Nayanthara", "Trisha Krishnan", "Kajal Aggarwal", "Tamannaah Bhatia", "Rakul Preet Singh",
        "Taapsee Pannu", "Vidya Balan", "Rani Mukerji", "Kajol", "Aishwarya Rai", "Madhuri Dixit",
        "Sridevi", "Hema Malini", "Rekha", "Zeenat Aman", "Parveen Babi", "Helen",
        "Waheeda Rehman", "Madhubala", "Meena Kumari", "Nargis", "Nutan", "Vyjayanthimala",
        "Sadhana", "Sharmila Tagore", "Jaya Bachchan", "Shabana Azmi", "Smita Patil",
        "Konkona Sen Sharma", "Radhika Apte", "Huma Qureshi", "Richa Chadha", "Nimrat Kaur",
        "Aditi Rao Hydari", "Sobhita Dhulipala", "Sanya Malhotra", "Fatima Sana Shaikh",
        "Mrunal Thakur", "Wamiqa Gabbi", "Tripti Dimri", "Medha Shankr", "Rasha Thadani",
        "Shanaya Kapoor", "Suhana Khan", "Khushi Kapoor", "Agastya Nanda", "Mihir Ahuja",
        "Vedang Raina", "Yuvraj Menda", "Dot.", "Aditi Saigal", "Zoya Akhtar", "Reema Kagti",
        "Farhan Akhtar", "Ritesh Sidhwani", "Karan Johar", "Sanjay Leela Bhansali",
        "Rajkumar Hirani", "S.S. Rajamouli", "Prashanth Neel", "Lokesh Kanagaraj",
        "Nelson Dilipkumar", "Atlee", "Sandeep Reddy Vanga", "Anurag Kashyap", "Vikramaditya Motwane",
        "Zoya Akhtar", "Konkona Sen Sharma", "Nandita Das", "Gauri Shinde", "Ashwiny Iyer Tiwari",
        "Meghna Gulzar", "Farah Khan", "Zoya Akhtar", "Reema Kagti", "Alankrita Shrivastava",
        "Nitya Mehra", "Shelly Chopra Dhar", "Tahira Kashyap", "Shonali Bose", "Mira Nair",
        "Deepa Mehta", "Gurinder Chadha", "Aparna Sen", "Rima Das", "Geetu Mohandas"
    ]
    
    musicians = [
        "Taylor Swift", "Dua Lipa", "Harry Styles", "The Weeknd", "Beyonce", "Rihanna", "Lady Gaga",
        "Adele", "Billie Eilish", "Olivia Rodrigo", "Ariana Grande", "Selena Gomez", "Justin Bieber",
        "Drake", "Kendrick Lamar", "J Cole", "Post Malone", "Ed Sheeran", "Bruno Mars", "Shawn Mendes",
        "Camila Cabello", "Halsey", "Lana Del Rey", "Lorde", "SZA", "Doja Cat", "Megan Thee Stallion",
        "Cardi B", "Nicki Minaj", "Lil Nas X", "Bad Bunny", "J Balvin", "Maluma", "Rosalia", "Karol G",
        "Daddy Yankee", "Anuel AA", "Ozuna", "Rauw Alejandro", "Myke Towers", "Bizarrap", "Quevedo",
        "Tini", "Lali", "Camilo", "Sebastian Yatra", "Nathy Peluso", "Trueno", "Duki", "Tiago PZK",
        "Maria Becerra", "Emilia", "Nicki Nicole", "Lit Killah", "Rusherking", "FMK", "Big One",
        "Arijit Singh", "Jubin Nautiyal", "Neha Kakkar", "Badshah", "Raftaar", "Divine", "Emiway Bantai",
        "Sidhu Moose Wala", "Diljit Dosanjh", "Guru Randhawa", "Yo Yo Honey Singh", "AP Dhillon",
        "Gurinder Gill", "Shubh", "Karan Aujla", "Amrit Maan", "Nimrat Khaira", "Sunanda Sharma",
        "Afshana Khan", "Jasleen Royal", "Prateek Kuhad", "Anuv Jain", "Ritviz", "When Chai Met Toast",
        "The Local Train", "Parvaaz", "Indian Ocean", "Euphoria", "Silk Route", "Strings", "Junoon",
        "Atif Aslam", "Rahat Fateh Ali Khan", "Ali Zafar", "Nusrat Fateh Ali Khan", "Abida Parveen",
        "Sanam Puri", "Armaan Malik", "Amaal Mallik", "Shreya Ghoshal", "Sunidhi Chauhan", "Monali Thakur",
        "Neeti Mohan", "Jonita Gandhi", "Shilpa Rao", "Alka Yagnik", "Kavita Krishnamurthy", "KS Chithra",
        "S Janaki", "P Susheela", "Lata Mangeshkar", "Asha Bhosle", "Kishore Kumar", "Mohammed Rafi",
        "Mukesh", "Manna Dey", "Hemant Kumar", "Talat Mahmood", "Mahendra Kapoor", "SP Balasubrahmanyam",
        "KJ Yesudas", "Hariharan", "Udit Narayan", "Kumar Sanu", "Abhijeet Bhattacharya", "Sonu Nigam",
        "Shaan", "KK", "Mohit Chauhan", "Benny Dayal", "Vishal Dadlani", "Shekhar Ravjiani", "Amit Trivedi",
        "AR Rahman", "Pritam", "Shankar Mahadevan", "Ehsaan Noorani", "Loy Mendonsa", "Sajid Khan",
        "Wajid Khan", "Salim Merchant", "Sulaiman Merchant", "Mithoon", "Ankit Tiwari", "Amaal Mallik",
        "Tanishk Bagchi", "Badshah", "Yo Yo Honey Singh", "Raftaar", "Ikka", "Lil Golu", "J Hind",
        "Bohemia", "Lazarus", "Deep Jandu", "Intense", "Steel Banglez", "Dr Zeus", "Rishi Rich",
        "Jay Sean", "Juggy D", "Veronica", "Raghav", "Panjabi MC", "Apache Indian", "Hard Kaur",
        "Ishq Bector", "Baba Sehgal", "Devang Patel", "Altaf Raja", "Adnan Sami", "Himesh Reshammiya"
    ]
    
    professions = [
        "accountant", "actor", "actress", "architect", "artist", "astronaut", "astronomer",
        "author", "baker", "banker", "barber", "bartender", "blacksmith", "biologist",
        "bricklayer", "butcher", "carpenter", "chef", "chemist", "cleaner", "clerk",
        "coach", "dentist", "designer", "detective", "diplomat", "doctor", "driver",
        "economist", "editor", "electrician", "engineer", "farmer", "firefighter",
        "fisherman", "florist", "gardener", "geologist", "graphic designer", "hairdresser",
        "historian", "journalist", "judge", "lawyer", "librarian", "lifeguard", "locksmith",
        "magician", "mechanic", "musician", "nurse", "optician", "painter", "pharmacist",
        "photographer", "physicist", "pilot", "plumber", "police officer", "politician",
        "postman", "priest", "professor", "programmer", "psychologist", "receptionist",
        "reporter", "sailor", "salesman", "scientist", "sculptor", "secretary", "security guard",
        "singer", "soldier", "surgeon", "tailor", "teacher", "technician", "translator",
        "truck driver", "undertaker", "veterinarian", "waiter", "waitress", "welder", "writer",
        "zoologist", "acupuncturist", "air traffic controller", "aircraft mechanic", "allergist",
        "ambulance driver", "anesthesiologist", "animal trainer", "animator", "appraiser",
        "arborist", "archaeologist", "armorer", "art director", "asbestos remover",
        "athletic trainer", "auctioneer", "audiologist", "auditor", "auto body repairer",
        "auto mechanic", "bailiff", "ballerina", "bank teller", "barista", "beautician",
        "bellhop", "bicycle repairer", "biochemist", "biomedical engineer", "blacksmith",
        "boat captain", "bodyguard", "bookkeeper", "botanist", "bouncer", "brewer",
        "broadcast technician", "broker", "budget analyst", "bus driver", "businessman",
        "businesswoman", "butler", "cabinetmaker", "cable installer", "calligrapher",
        "camera operator", "canvasser", "cardiologist", "career counselor", "caretaker",
        "cartoonist", "cashier", "casino dealer", "caterer", "cell biologist", "chaplain",
        "chauffeur", "chemical engineer", "chief executive", "childcare worker", "chiropractor",
        "choreographer", "civil engineer", "claims adjuster", "clergy", "clinical psychologist",
        "cobbler", "coder", "coffee roaster", "collector", "comedian", "commercial pilot",
        "community organizer", "composer", "computer programmer", "concierge", "conductor",
        "conservationist", "construction worker", "consultant", "cook", "copywriter",
        "coroner", "corrections officer", "cosmetologist", "costume designer", "counselor",
        "courier", "court reporter", "crane operator", "crematory operator", "critic",
        "cryptographer", "curator", "customer service rep", "customs inspector", "dancer",
        "data analyst", "data scientist", "database administrator", "daycare provider",
        "dean", "debt collector", "decorator", "delivery driver", "demolition expert",
        "dental hygienist", "dermatologist", "desk clerk", "desktop publisher", "developer",
        "dietitian", "digital marketer", "director", "dishwasher", "dispatcher", "distiller",
        "diver", "dj", "dockworker", "dog walker", "doorman", "drafter", "dramaturg",
        "dressmaker", "drummer", "dry cleaner", "ecologist", "econometrician", "editor-in-chief",
        "educational consultant", "elderly caregiver", "electrical engineer", "electrician",
        "electrologist", "elementary school teacher", "elevator mechanic", "embalmer",
        "embroidery machine operator", "emergency dispatcher", "emergency medical technician",
        "endocrinologist", "energy auditor", "engineer", "english teacher", "engraver",
        "entomologist", "entrepreneur", "environmental scientist", "epidemiologist",
        "escrow officer", "esthetician", "ethicist", "ethnographer", "event planner",
        "eviction officer", "excavator operator", "executive assistant", "exercise physiologist",
        "exorcist", "experimental psychologist", "exterminator", "fabricator", "factory worker",
        "family therapist", "farm manager", "fashion designer", "fashion model", "fast food worker",
        "fence builder", "ferry captain", "fiber optic technician", "file clerk", "film director",
        "film editor", "film producer", "financial advisor", "financial analyst", "financial planner",
        "fine artist", "fire investigator", "firefighter", "first mate", "fish and game warden",
        "fitness instructor", "flight attendant", "floor layer", "florist", "folklorist",
        "food scientist", "food stylist", "foreman", "forensic scientist", "forest ranger",
        "forestry technician", "forklift operator", "foundry worker", "framer", "freelancer",
        "french teacher", "front desk clerk", "funeral director", "furniture designer",
        "furniture maker", "game designer", "game developer", "game warden", "garbage collector",
        "gas station attendant", "gastroenterologist", "gemologist", "genealogist", "general contractor",
        "general practitioner", "genetic counselor", "geneticist", "geographer", "geologist",
        "geophysicist", "german teacher", "gerontologist", "glass blower", "glazier",
        "goldsmith", "golf pro", "government official", "governess", "graduate student",
        "granite installer", "graphic artist", "greenhouse worker", "greeter", "grill cook",
        "groomer", "groundskeeper", "guard", "guitarist", "gunsmith", "gym teacher",
        "gymnast", "gynecologist", "haberdasher", "hair stylist", "handyman", "harbor master",
        "hat maker", "head hunter", "headmaster", "health coach", "health inspector",
        "hearing aid specialist", "heart surgeon", "heavy equipment operator", "hedge fund manager",
        "helper", "hematologist", "herbalist", "high school teacher", "highway patrol officer",
        "hiker", "historian", "hitchhiker", "hobbyist", "home health aide", "home inspector",
        "home stager", "homeopath", "homemaker", "hooker", "horse trainer", "horticulturist",
        "hospice worker", "hospital administrator", "host", "hostess", "hotel manager",
        "house painter", "housekeeper", "human resources manager", "hunter", "hussar",
        "hydrologist", "hygienist", "hypnotherapist", "ice cream maker", "ichthyologist",
        "illustrator", "immunologist", "importer", "industrial designer", "industrial engineer",
        "infantryman", "infectious disease specialist", "influencer", "information architect",
        "information security analyst", "ink maker", "innkeeper", "inspector", "installer",
        "instructor", "instrument maker", "insulator", "insurance agent", "insurance underwriter",
        "intellectual property lawyer", "intelligence officer", "interior decorator",
        "interior designer", "intern", "interpreter", "interrogator", "inventor", "investigator",
        "investment banker", "ironworker", "irrigation specialist", "it consultant",
        "it manager", "it specialist", "it technician", "jailer", "janitor", "japanese teacher",
        "jazz musician", "jeweler", "jockey", "joiner", "journalist", "judge", "juggler",
        "judicial clerk", "junior developer", "junior engineer", "justiciar", "karate instructor",
        "kennel attendant", "keyboardist", "king", "kitchen manager", "knitter", "lab assistant",
        "lab technician", "laborer", "land surveyor", "landscaper", "language teacher",
        "lapidary", "laser technician", "lathe operator", "laundry worker", "law clerk",
        "law enforcement officer", "lawyer", "lead singer", "leather worker", "lecturer",
        "legal assistant", "legal secretary", "legislator", "lens grinder", "librarian",
        "licensed practical nurse", "life coach", "lifeguard", "lighting designer",
        "lighting technician", "limousine driver", "linguist", "lineman", "lineworker",
        "literary agent", "lithographer", "loan officer", "lobbyist", "local politician",
        "locksmith", "logger", "logistics coordinator", "logistics manager", "loom operator",
        "lyricist", "machine operator", "machinist", "madam", "magician", "magistrate",
        "maid", "mail carrier", "maintenance worker", "makeup artist", "manager",
        "manicurist", "manufacturer", "marine biologist", "marine engineer", "marine surveyor",
        "market researcher", "marketing coordinator", "marketing director", "marketing manager",
        "marriage counselor", "martial artist", "mason", "massage therapist", "master",
        "master of ceremonies", "mathematical modeler", "mathematician", "matron", "mayor",
        "meat cutter", "mechanic", "mechanical engineer", "mediator", "medical assistant",
        "medical coder", "medical director", "medical examiner", "medical illustrator",
        "medical lab technician", "medical physicist", "medical records clerk", "medical secretary",
        "medical student", "medical transcriptionist", "medicinal chemist", "mental health counselor",
        "mercenary", "merchant", "merchant seaman", "messenger", "metal worker",
        "metallurgist", "meteorologist", "meter reader", "microbiologist", "midwife",
        "military officer", "military pilot", "military police", "military scientist",
        "milkman", "milliner", "millwright", "mime", "miner", "minister", "missionary",
        "mixologist", "model", "model maker", "moderator", "monk", "mortician",
        "mortgage broker", "mosaic artist", "motivational speaker", "motorcycle mechanic",
        "mountain guide", "mover", "movie star", "museum curator", "museum director",
        "music composer", "music conductor", "music director", "music producer",
        "music teacher", "music therapist", "musician", "mycologist", "nanny",
        "nanotechnologist", "narrator", "naturalist", "naturopath", "naval officer",
        "navigator", "negotiator", "neonatal nurse", "nephrologist", "network administrator",
        "network analyst", "network engineer", "neurologist", "neuropsychologist",
        "neurosurgeon", "news anchor", "news reporter", "night shift worker", "night watchman",
        "ninja", "non-profit director", "notary public", "novelist", "nuclear engineer",
        "nuclear physicist", "nuclear technician", "numismatist", "nurse", "nurse anesthetist",
        "nurse practitioner", "nursery worker", "nutritionist", "obstetrician", "occupational therapist",
        "oceanographer", "office assistant", "office manager", "office worker", "officer",
        "official", "oil rigger", "oncologist", "opera singer", "operations manager",
        "ophthalmologist", "optical technician", "optician", "optometrist", "oral surgeon",
        "orchestra conductor", "orderly", "organist", "ornithologist", "orthodontist",
        "orthopedic surgeon", "osteopath", "otolaryngologist", "outdoorsman", "package designer",
        "packer", "pagan priest", "pager", "pain management specialist", "painter",
        "paleontologist", "pallet jack operator", "pantry chef", "paralegal", "paramedic",
        "parishioner", "park ranger", "parking attendant", "parole officer", "parson",
        "pastor", "patent agent", "patent attorney", "patent examiner", "pathologist",
        "patriot", "patrol officer", "pattern maker", "pavement saw operator", "pawn shop owner",
        "paymaster", "payroll clerk", "pediatrician", "pedicurist", "perfumer", "performer",
        "periodontist", "personal assistant", "personal shopper", "personal trainer",
        "pest control technician", "pet sitter", "pet stylist", "petroleum engineer",
        "pharmacist", "pharmacology professor", "philanthropist", "philosopher",
        "phlebotomist", "phonology expert", "photogrammetrist", "photographer",
        "photographic retoucher", "photojournalist", "physical therapist", "physician",
        "physician assistant", "physicist", "physiologist", "physiotherapist", "pianist",
        "piano tuner", "picker", "picket", "pilot", "pipe fitter", "plasterer",
        "plastic surgeon", "plate maker", "playwright", "plumber", "podcaster",
        "podiatrist", "poet", "police captain", "police chief", "police detective",
        "police officer", "police sergeant", "polisher", "political analyst", "political consultant",
        "political scientist", "politician", "pool cleaner", "pope", "porter", "portrait painter",
        "postal clerk", "postal worker", "poster", "potter", "poultry farmer", "powder monkey",
        "power plant operator", "preacher", "prefect", "prelate", "president", "press agent",
        "press secretary", "priest", "primary school teacher", "prime minister", "principal",
        "printmaker", "prison guard", "prison warden", "private investigator", "private tutor",
        "probation officer", "proctologist", "producer", "product designer", "product manager",
        "professor", "programmer", "project manager", "promoter", "proofreader", "property manager",
        "prosecutor", "prostitute", "psychiatric nurse", "psychiatrist", "psychic", "psychoanalyst",
        "psychologist", "psychotherapist", "public relations specialist", "publisher", "pundit",
        "puppeteer", "purchasing agent", "quality control inspector", "quantity surveyor",
        "quantum physicist", "quarry worker", "queen", "rabbi", "radar technician",
        "radiographer", "radiologist", "radiology technician", "railroad engineer",
        "railroad worker", "rancher", "ranger", "real estate agent", "real estate broker",
        "receptionist", "recording engineer", "records manager", "recreation leader",
        "recruiter", "referee", "refining technician", "refrigeration mechanic", "registrar",
        "rehabilitation counselor", "religious leader", "renaissance man", "repairman",
        "reporter", "representative", "research assistant", "research scientist", "researcher",
        "respiratory therapist", "restaurant manager", "restaurateur", "retail clerk",
        "retail manager", "retail worker", "retired person", "reviewer", "rhetorician",
        "rigging grip", "riot police", "ripper", "roboticist", "robotics engineer",
        "rock star", "roofer", "room service attendant", "rope maker", "rower", "royal",
        "rubber worker", "rug maker", "ruler", "runner", "rural mail carrier", "sacristan",
        "saddler", "safety coordinator", "safety engineer", "safety inspector", "sailor",
        "sales associate", "sales clerk", "sales director", "sales manager", "sales representative",
        "salesperson", "salvage diver", "salvage worker", "sampler", "sanitation worker",
        "satellite engineer", "saxophonist", "scaffolder", "scholar", "school bus driver",
        "school counselor", "school nurse", "school principal", "school psychologist",
        "school teacher", "scientist", "scout", "scoutmaster", "screenwriter", "sculptor",
        "sea captain", "seamstress", "search and rescue worker", "seasonal worker",
        "secateur", "secretary", "security analyst", "security consultant", "security guard",
        "security officer", "security specialist", "seismologist", "senator", "senior citizen",
        "senior developer", "senior engineer", "senior manager", "sergeant", "servant",
        "server", "service manager", "service technician", "service worker", "sewer",
        "sewing machine operator", "shaman", "sharpshooter", "sheep shearer", "shepherd",
        "sheriff", "ship captain", "ship builder", "shipwright", "shoemaker", "shop assistant",
        "shopkeeper", "shunter", "siding installer", "sign language interpreter", "sign maker",
        "signal analyst", "signal operator", "silversmith", "singer", "singer-songwriter",
        "sister", "sketch artist", "ski instructor", "skilled tradesman", "skin care specialist",
        "skydiver", "slaughterhouse worker", "sleeper", "small business owner", "smokejumper",
        "smuggler", "soap maker", "soccer player", "social media manager", "social science researcher",
        "social worker", "sociologist", "software architect", "software developer", "software engineer",
        "software tester", "soil scientist", "soldier", "solicitor", "soloist", "sommelier",
        "sonar technician", "songwriter", "sound designer", "sound engineer", "sound mixer",
        "sound technician", "sous chef", "space scientist", "special agent", "special education teacher",
        "special forces soldier", "specialist", "speech language pathologist", "speech therapist",
        "speechwriter", "spelunker", "spinner", "spiritual leader", "sports agent",
        "sports coach", "sports commentator", "sports journalist", "sports photographer",
        "sports player", "spy", "squire", "stable hand", "stage director", "stage manager",
        "stand-up comedian", "star", "stargazer", "state trooper", "station master",
        "statistician", "statutory auditor", "steam fitter", "steeplejack", "stenographer",
        "stevedore", "steward", "stewardess", "stock broker", "stock clerk", "stock trader",
        "stone carver", "stone mason", "store manager", "storyteller", "strategist",
        "street performer", "street sweeper", "street vendor", "stunt double", "stunt performer",
        "stylist", "subcontractor", "submarine officer", "subway driver", "sugar refiner",
        "supervisor", "superintendent", "surgeon", "surgical assistant", "surgical technologist",
        "surveyor", "sushi chef", "swimming instructor", "swimsuit model", "switchboard operator",
        "sword maker", "synagogue leader", "synthetic biologist", "systems administrator",
        "systems analyst", "systems engineer", "tailor", "tank commander", "tanner",
        "tattoo artist", "tax accountant", "tax attorney", "tax collector", "tax examiner",
        "tax inspector", "taxi driver", "taxidermist", "teacher", "teacher's aide",
        "team leader", "tech support", "technical advisor", "technical director",
        "technical lead", "technical writer", "technician", "technologist", "telecommunications technician",
        "telemarketer", "telephone operator", "telesales representative", "television presenter",
        "teller", "temp", "tennis player", "terminal manager", "termite inspector", "tester",
        "textile designer", "textile worker", "theater director", "theater manager",
        "theological student", "theologian", "theoretical physicist", "therapist", "thinker",
        "third mate", "ticket agent", "ticket collector", "tile setter", "tiller",
        "timekeeper", "tinsmith", "tire technician", "tobacco farmer", "toll collector",
        "tool and die maker", "tool maker", "topographer", "tour guide", "town clerk",
        "town crier", "town planner", "toxicologist", "toy maker", "track coach",
        "tractor driver", "trader", "tradesman", "traditional healer", "traffic controller",
        "traffic engineer", "traffic warden", "train conductor", "train driver", "trainer",
        "transcriptionist", "translator", "transmission technician", "transport manager",
        "transportation engineer", "trapeze artist", "trapper", "trash collector",
        "travel agent", "travel consultant", "travel writer", "treasurer", "tree surgeon",
        "trial lawyer", "tribal leader", "truck driver", "trucker", "trumpeter",
        "trustee", "tugboat captain", "tutor", "typesetter", "typist", "typographer",
        "urologist", "ushas", "usher", "utility worker", "vampire hunter", "van driver",
        "vaporware developer", "variety performer", "vasectomy specialist", "vatican official",
        "vaudeville performer", "vault manager", "vault technician", "vegetable farmer",
        "vending machine repairer", "venereologist", "ventriloquist", "verger", "vestryman",
        "veterans advocate", "veterinarian", "veterinary assistant", "veterinary surgeon",
        "vicar", "vice president", "victim advocate", "video editor", "video game developer",
        "video producer", "videographer", "vigilante", "viking", "vintner", "violinist",
        "virologist", "virtual assistant", "visitor", "visual artist", "visual designer",
        "vocalist", "vocational counselor", "voice actor", "voice coach", "volunteer",
        "waiter", "waitress", "warden", "warehouse manager", "warehouse worker",
        "warrior", "warship captain", "washwoman", "waste collector", "waste management expert",
        "watchmaker", "water quality technician", "weaver", "web designer", "web developer",
        "wedding planner", "weed puller", "welder", "welfare worker", "well driller",
        "west end performer", "wet nurse", "whale watcher", "whistleblower", "wildlife biologist",
        "wildlife photographer", "winemaker", "wireman", "witch", "witch doctor",
        "witness", "wood carver", "woodworker", "word processor", "work coach",
        "worker", "workout instructor", "writer", "x-ray technician", "yacht captain",
        "yard worker", "yoga instructor", "youth worker", "zen master", "zookeeper", "zoologist"
    ]
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write("celebs:\n")
        f.write("  actors:\n")
        f.write("    male:\n")
        for item in male_actors:
            f.write(f"    - {item}\n")
        f.write("    female:\n")
        for item in female_actors:
            f.write(f"    - {item}\n")
        f.write("  musicians:\n")
        for item in musicians:
            f.write(f"    - {item}\n")
        f.write("professions:\n")
        for item in professions:
            f.write(f"  - {item}\n")

def expand_styles():
    file_path = os.path.join(base_dir, "art", "styles.yaml")
    
    styles = [
        "renaissance", "baroque", "rococo", "neoclassicism", "romanticism", "realism", "impressionism",
        "post-impressionism", "expressionism", "fauvism", "cubism", "futurism", "dadaism", "surrealism",
        "abstract expressionism", "pop art", "minimalism", "conceptual art", "photorealism", "hyperrealism",
        "art nouveau", "art deco", "bauhaus", "de stijl", "constructivism", "suprematism", "metaphysical art",
        "social realism", "precisionism", "regionalism", "color field painting", "hard-edge painting",
        "op art", "arte povera", "land art", "performance art", "video art", "digital art", "pixel art",
        "vector art", "3d art", "glitch art", "generative art", "ai art", "street art", "graffiti",
        "stencil art", "lowbrow art", "pop surrealism", "cyberpunk", "steampunk", "vaporwave", "synthwave",
        "dieselpunk", "atompunk", "solarpunk", "biopunk", "nanopunk", "cassette futurism", "formpunk",
        "dark academia", "light academia", "cottagecore", "fairycore", "goblincore", "witchcore",
        "angelcore", "demoncore", "spacecore", "oceaneye", "aesthetic", "brutalism", "deconstructivism",
        "postmodernism", "modernism", "contemporary art", "outsider art", "folk art", "naive art",
        "primitive art", "tribal art", "aboriginal art", "inuit art", "maori art", "aztec art",
        "mayan art", "incan art", "ancient egyptian art", "ancient greek art", "ancient roman art",
        "byzantine art", "islamic art", "persian art", "indian art", "chinese art", "japanese art",
        "korean art", "african art", "oceanic art", "pre-columbian art", "medieval art", "romanesque art",
        "gothic art", "international gothic", "northern renaissance", "mannerism", "tenebrism",
        "chiaroscuro", "sfumato", "uvenile art", "psychotropic art", "psychedelic art", "fractal art",
        "kinetic art", "light art", "installation art", "site-specific art", "environmental art",
        "eco art", "sustainable art", "bio art", "body art", "tattoo art", "makeup art", "fashion art",
        "sculptural art", "installation", "happening", "fluxus", "neo-dada", "new realism",
        "nuovo realismo", "figuration libre", "transavantgarde", "neo-expressionism", "bad painting",
        "new image painting", "neo-geo", "commodification art", "young british artists", "stuckism",
        "superflat", "remix culture", "appropriation art", "internet art", "net art", "software art",
        "ascii art", "ansi art", "teletext art", "videotex art", "demo scene art", "chiptune art",
        "pixelated style", "8-bit art", "16-bit art", "low poly art", "high poly art", "pbr render",
        "raytraced", "unreal engine render", "unity render", "octane render", "redshift render",
        "vray render", "arnold render", "cycles render", "eevee render", "blender art",
        "zbrush sculpt", "mudbox sculpt", "cinema 4d art", "maya art", "3ds max art",
        "houdini art", "substance painter art", "photoshop art", "illustrator art",
        "inkscape art", "gimp art", "krita art", "procreate art", "corel painter art",
        "clip studio paint art", "sai art", "medibang art", "firealpaca art", "aseprite art",
        "piskel art", "magica voxel art", "quixel art", "megascans art", "speedtree art",
        "terragen art", "bryce 3d art", "vue art", "poser art", "daz 3d art", "vroid art",
        "metahuman art", "deepfake art", "neural style transfer", "stable diffusion art",
        "midjourney art", "dall-e art", "craiyon art", "nightcafe art", "artbreeder art",
        "runway ml art", "ebsynth art", "kaiber art", "pika labs art", "sora art",
        "dreamstudio art", "leonardo ai art", "lexica art", "playground ai art", "clipdrop art",
        "adobe firefly art", "canva ai art", "bing image creator art", "google imagen art",
        "meta emu art", "apple intelligence art", "nvidia canvas art", "gaugan art",
        "deep dream art", "stylegan art", "biggan art", "vqgan art", "clip art",
        "modernism", "post-modernism", "minimalism", "maximalism", "brutalism", "futurism",
        "constructivism", "deconstructivism", "biomorphism", "organic design", "industrial design",
        "scandinavian design", "japanese zen design", "bauhaus design", "mid-century modern",
        "art deco", "art nouveau", "victorian", "edwardian", "regency", "georgian",
        "baroque", "rococo", "renaissance", "gothic", "romanesque", "byzantine", "classical",
        "ancient greek", "ancient roman", "ancient egyptian", "ancient mesopotamian",
        "prehistoric", "tribal", "folk", "craft", "hand-made", "diy style", "maker culture",
        "hacker aesthetic", "cypherpunk", "solarpunk", "lunarpunk", "steampunk", "clockpunk",
        "dieselpunk", "atompunk", "raypunk", "cassette futurism", "vaporwave", "synthwave",
        "retrowave", "outrun", "cybercore", "glitchcore", "webcore", "old web", "90s web",
        "y2k aesthetic", "frutiger aero", "skeuomorphism", "flat design", "neumorphism",
        "glassmorphism", "claymorphism", "aurora design", "bento design", "card design",
        "material design", "fluent design", "human interface guidelines", "metro ui",
        "windows 95 aesthetic", "mac os classic aesthetic", "commodore 64 art",
        "amiga art", "atari art", "nes art", "snes art", "genesis art", "ps1 aesthetic",
        "n64 aesthetic", "dreamcast aesthetic", "ps2 aesthetic", "gamecube aesthetic",
        "xbox aesthetic", "wii aesthetic", "ds aesthetic", "psp aesthetic", "mobile ui design",
        "app design", "ux design", "ui design", "product design", "graphic design",
        "branding", "identity design", "logo design", "typography", "lettering",
        "calligraphy", "graffiti art", "street art", "mural art", "poster art",
        "editorial design", "book design", "magazine design", "newspaper design",
        "advertising art", "commercial art", "packaging design", "web design",
        "interface design", "interaction design", "experience design", "service design",
        "strategic design", "systemic design", "speculative design", "critical design",
        "adversarial design", "inclusive design", "universal design", "accessible design",
        "sustainable design", "circular design", "eco-friendly design", "green design",
        "biophilic design", "regenerative design", "resilient design", "futures design",
        "anticipatory design", "transition design", "social design", "participatory design",
        "co-design", "user-centered design", "human-centered design", "life-centered design",
        "planet-centered design", "earth-centered design", "cosmos-centered design",
        "metaphysical design", "spiritual design", "sacred geometry", "fractal design",
        "generative design", "algorithmic design", "parametric design", "computational design",
        "ai-driven design", "robotic design", "automated design", "synthetic design",
        "biological design", "living design", "growing design", "evolving design",
        "quantum design", "multidimensional design", "interstellar design", "galactic design",
        "universal design", "infinite design", "eternal design", "absolute design"
    ]
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write("styles:\n")
        for item in styles:
            f.write(f"  - {item}\n")

expand_celebs()
expand_styles()

print("Expanded celebs and styles.")
