import os

file_path = r"c:\Users\91797\Documents\Dev\JS\Monorepo\Backend Monorepo\Resources\wildcards\places\environments.yaml"

residential_items = [
    "modern living room", "cozy bedroom", "rustic kitchen", "minimalist bathroom", "sunlit attic",
    "spacious basement", "home office", "gaming room", "home theater", "wine cellar", "pantry",
    "laundry room", "walk-in closet", "nursery", "guest room", "art studio", "music room",
    "workshop", "garage", "conservatory", "sunroom", "balcony", "veranda", "foyer", "hallway",
    "dining room", "breakfast nook", "mudroom", "library", "reading nook", "meditation room",
    "home gym", "sauna", "indoor pool", "trophy room", "craft room", "sewing room", "darkroom",
    "man cave", "she shed interior", "hidden panic room", "bunker", "attic crawl space",
    "basement storage", "utility room", "server room", "home bar", "billiard room", "cigar lounge",
    "safe room", "observatory", "loft", "studio apartment", "penthouse living room",
    "luxury suite", "standard hotel room", "motel room", "cabin interior", "cottage living space",
    "farmhouse kitchen", "barn conversion interior", "treehouse room", "houseboat cabin",
    "rv interior", "camper van living space", "tiny house interior", "container home room",
    "underground house chamber", "earthship interior", "igloo interior", "tent interior",
    "yurt living space", "teepee interior", "mansion grand hall", "palace bedroom",
    "castle chamber", "manor study", "estate library", "villa lounge", "chalet living room",
    "bungalow bedroom", "townhouse kitchen", "duplex living space", "condo balcony",
    "shack interior", "dilapidated room", "abandoned house hallway", "haunted bedroom",
    "vintage 70s living room", "80s retro bedroom", "90s teenage room", "victorian parlor",
    "edwardian dining room", "renaissance bedchamber", "medieval peasant hut interior",
    "ancient roman atrium", "greek courtyard room", "japanese washitsu", "zen tea room",
    "scandinavian living space", "bohemian bedroom", "industrial loft", "mid-century modern lounge",
    "art deco dining area", "gothic revival library", "steampunk workshop", "cyberpunk apartment",
    "futuristic modular room", "space station living quarters", "alien habitat interior",
    "underwater base room", "submarine cabin", "airplane cabin", "train sleeper car",
    "bus interior living area", "car interior", "van life setup", "backyard shed office",
    "greenhouse interior", "pool house lounge", "carriage house flat", "granny flat",
    "basement apartment", "attic studio", "rooftop garden room", "secret attic room",
    "hidden basement bar", "wine tasting room", "cheese cellar", "root cellar", "storm cellar",
    "fallout shelter", "emergency bunker", "survivalist cache", "prepper pantry",
    "walk-in pantry", "scullery", "butler's pantry", "formal dining hall", "banquet hall",
    "ballroom", "grand staircase hall", "vestibule", "cloakroom", "powder room",
    "ensuite bathroom", "jack and jill bathroom", "spa bathroom", "outdoor shower area",
    "covered patio", "screened-in porch", "wrap-around porch", "deck area", "fire pit lounge",
    "home observatory", "telescope room", "stargazing deck", "hobby room", "tool shed",
    "potting shed", "garden room", "bird watching room", "cat patio", "dog room",
    "pet grooming station", "aquarium room", "terrarium lounge", "indoor garden",
    "vertical garden wall room", "hydroponic room", "smoking room", "hookah lounge",
    "gaming den", "vr setup room", "pc gaming station", "console gaming corner",
    "retro arcade room", "pinball lounge", "board game room", "poker room", "casino room",
    "private cinema", "screening room", "recording studio", "mixing room", "vocal booth",
    "rehearsal space", "dance studio", "yoga studio", "pilates room", "massage room",
    "therapy room", "healing space", "altar room", "prayer room", "chapel interior",
    "sanctuary", "zen garden room", "indoor rock climbing wall", "trampoline room",
    "skate ramp room", "indoor halfpipe", "bowling alley room", "shooting range room",
    "archery range room", "fencing salle", "dojo", "martial arts room", "boxing gym",
    "ballet barre room", "stage room", "theater rehearsal hall", "costume room",
    "makeup vanity room", "wig room", "fashion closet", "shoe room", "handbag display room",
    "jewelry vault", "watch collection room", "coin collection room", "stamp collection room",
    "comic book library", "vinyl record room", "dj booth", "home radio station",
    "podcasting studio", "video editing suite", "photography studio", "green screen room",
    "motion capture studio", "robotics lab", "3d printing room", "electronics workbench",
    "carpentry shop", "metalworking shop", "pottery studio", "glassblowing studio",
    "weaving room", "spinning room", "knitting nook", "quilting room", "scrapbooking corner",
    "calligraphy desk", "writing room", "poet's corner", "scholar's study", "professor's library",
    "scientist's home lab", "inventor's attic", "alchemist's basement", "wizard's tower room",
    "witch's kitchen", "herbalist's room", "apothecary's nook", "botanist's sunroom",
    "astronomer's dome", "navigator's room", "explorer's trophy hall", "hunter's lodge interior",
    "fisherman's shack interior", "lumberjack cabin interior", "miner's cottage interior",
    "shepherd's hut interior", "nomad's tent interior", "caravan interior", "circus wagon interior",
    "gypsy wagon interior", "steamboat cabin", "luxury yacht lounge", "private jet interior",
    "limousine interior", "classic car interior", "vintage bus interior", "modern train interior",
    "maglev train cabin", "space shuttle interior", "mars colony habitat", "lunar base room",
    "asteroid base corridor", "generation ship living space", "cryo sleep chamber",
    "cloning lab interior", "bio-dome living area", "floating city apartment",
    "cloud city penthouse", "underground city dwelling", "subterranean home",
    "cave dwelling interior", "cliff house room", "waterfall house interior",
    "island villa lounge", "desert house courtyard", "mountain lodge living room",
    "jungle hut interior", "swamp house room", "beach house bedroom", "lake house deck",
    "river house porch", "canal house attic", "windmill interior", "lighthouse living quarters",
    "watchtower room", "gatehouse chamber", "fortress hall", "citadel room", "keep interior",
    "bastion chamber", "armory", "guard room", "barracks room", "mess hall",
    "officer's quarters", "commander's office", "strategy room", "war room", "throne room",
    "audience chamber", "council hall", "courtroom", "jail cell", "dungeon chamber",
    "torture room", "execution chamber", "morgue", "funeral parlor", "crematorium",
    "columbarium", "catacomb chamber", "crypt", "vault", "treasure chamber", "gold room",
    "bank vault interior", "safe deposit room", "money counting room", "stock exchange floor",
    "trading floor", "brokerage office", "boardroom", "executive suite", "ceo office",
    "cubicle farm", "open plan office", "coworking space", "reception area", "lobby",
    "waiting room", "breakroom", "cafeteria", "canteen", "kitchenette", "vending machine area",
    "mailroom", "copy room", "file room", "archive", "records room", "evidence room",
    "interrogation room", "observation room", "control room", "monitoring station",
    "dispatch center", "operations center", "command center", "data center", "server farm",
    "mainframe room", "supercomputer hall", "clean room", "bio-hazard lab", "chemical lab",
    "physics lab", "engineering lab", "prototype shop", "testing facility", "quality control lab",
    "assembly line", "factory floor", "warehouse aisle", "shipping dock", "receiving area",
    "loading bay", "inventory room", "supply closet", "janitor's closet", "boiler room",
    "electrical room", "hvac room", "elevator machine room", "pump room", "water treatment area",
    "waste management room", "recycling center", "composting area", "incinerator room",
    "generator room", "battery room", "solar inverter room", "telecom closet", "patch panel room",
    "wiring closet", "plumbing chase", "crawl space", "void space", "maintenance tunnel",
    "access shaft", "ventilation duct", "chimney interior", "flue", "firebox", "fireplace",
    "hearth area", "inglenook", "alcove", "niche", "recess", "window seat", "bay window area",
    "oriel window nook", "skylight area", "atrium floor", "mezzanine level", "gallery",
    "catwalk", "scaffolding area", "loft bed area", "bunk bed room", "dormitory", "hostel room",
    "barracks", "sleeping pod", "capsule hotel room", "sleeper sofa area", "murphy bed room",
    "daybed nook", "chaise longue area", "recliner corner", "armchair nook", "fireplace lounge",
    "conversation pit", "sunken living room", "raised platform room", "split level room",
    "open concept living", "modular living space", "transforming apartment", "smart home interior",
    "voice controlled room", "gesture controlled area", "holographic display room",
    "augmented reality space", "virtual reality room", "matrix style interface room",
    "neural link station", "cybernetic chair room", "bio-interface lab", "cloning tank room",
    "stasis pod room", "hibernation chamber", "escape pod interior", "airlock chamber",
    "decontamination room", "quarantine zone", "isolation ward", "high security cell",
    "padded room", "rubber room", "white room", "black room", "red room", "blue room",
    "green room", "yellow room", "color coded chamber", "sensory deprivation tank room",
    "isolation tank room", "float tank room", "meditation pod", "sleep capsule",
    "dream recording room", "memory extraction lab", "mind upload station",
    "digital afterlife server room", "virtual heaven interior", "virtual hell interior",
    "glitchy reality room", "fractal room", "impossible geometry room", "escher style room",
    "non-euclidean space", "tesseract interior", "wormhole interior", "black hole interior",
    "white hole interior", "cosmic void room", "starlit chamber", "nebula room", "galaxy hall",
    "universe room", "multiverse hub", "time travel station", "teleportation pad room",
    "portal room", "dimensional gate room", "stargate chamber", "infinity room",
    "mirror maze interior", "hall of mirrors", "glass house interior", "ice house interior",
    "crystal palace room", "diamond chamber", "gold leaf room", "silver lined hall",
    "bronze age room", "iron age chamber", "stone age cave", "prehistoric dwelling",
    "dinosaur age habitat", "future primitive hut", "solarpunk living space",
    "biopunk habitat", "nanopunk room", "clockpunk workshop", "dieselpunk lounge",
    "atompunk kitchen", "raypunk bridge", "silkpunk chamber", "woodpunk interior",
    "formpunk room", "minimalist white room", "maximalist cluttered room", "hoarder's room",
    "collector's paradise", "museum of self", "personal shrine", "altar to the unknown",
    "hidden temple interior", "secret society meeting room", "illuminati boardroom",
    "freemason hall", "templar chapel", "assassin's hideout", "thieves' den",
    "pirate captain's cabin", "smuggler's hold", "underground railroad station",
    "speakeasy interior", "prohibition era bar", "jazz club lounge", "blues bar interior",
    "rock club stage", "punk venue pit", "techno club floor", "rave warehouse interior",
    "disco dance floor", "ballroom dance floor", "swing dance hall", "tango salon",
    "salsa club", "flamenco stage", "ballet rehearsal room", "opera house stage",
    "concert hall stage", "orchestra pit", "recording booth", "radio dj studio",
    "television studio set", "film set interior", "theater stage", "backstage dressing room",
    "green room lounge", "wardrobe room", "prop room", "scenery shop", "lighting booth",
    "sound booth", "projection booth", "cinema auditorium", "imax theater", "4dx theater",
    "drive-in car interior", "outdoor theater seating", "amphitheater stage", "stadium locker room",
    "gymnasium floor", "locker room", "shower room", "equipment room", "training room",
    "medical room", "coach's office", "press box", "luxury box", "skybox", "viplounge",
    "members only club", "exclusive resort lobby", "spa reception", "massage treatment room",
    "facial room", "manicure station", "pedicure chair", "hair salon station", "barber chair",
    "tattoo parlor station", "piercing room", "body mod clinic", "plastic surgery suite",
    "operating theater", "recovery room", "patient room", "intensive care unit",
    "emergency room bay", "triage area", "ambulance interior", "helicopter interior",
    "coast guard boat interior", "fire truck cab", "police car back seat", "swat van interior",
    "military transport interior", "tank interior", "fighter jet cockpit", "bomber bridge",
    "submarine control room", "aircraft carrier deck control", "mission control center",
    "launch pad control", "satellite ground station", "deep space network room",
    "alien abduction room", "ufo interior", "mothership bridge", "scout ship cockpit",
    "fighter pod interior", "escape pod", "cryo pod", "stasis field", "energy field room",
    "force field chamber", "gravity well room", "zero-g chamber", "vacuum chamber",
    "pressure chamber", "anechoic chamber", "soundproof room", "tempest room",
    "wind tunnel interior", "lightning lab", "plasma chamber", "fusion reactor hall",
    "particle accelerator tunnel", "hadron collider room", "quantum computer room",
    "qubit storage area", "entanglement lab", "teleportation station", "replicator room",
    "holodeck", "virtual reality grid", "cyberspace hub", "internet backbone room",
    "undersea cable station", "satellite uplink room", "radio telescope control",
    "weather station interior", "volcano observatory", "earthquake monitor room",
    "tsunami warning center", "nuclear power plant control", "hydroelectric dam control",
    "wind farm monitor room", "solar farm control", "grid management center",
    "city traffic control", "air traffic control tower", "railway signal box",
    "maritime traffic center", "space traffic control", "galactic hub station",
    "interstellar gate control", "dimension hop station", "time bridge room",
    "eternity's end chamber", "beginning of time room", "end of the universe room",
    "void between worlds", "liminal space room", "backrooms level", "dream world bedroom",
    "nightmare world corridor", "purgatory waiting room", "underworld gatehouse",
    "heavenly gate hall", "divine audience room", "angelic choir hall", "demonic council room",
    "hellish torture chamber", "purgatory filing room", "cosmic justice court",
    "reincarnation center", "soul sorting room", "destiny's loom room", "fate's library",
    "akashic records room", "hall of records", "vault of knowledge", "well of souls room",
    "fountain of youth room", "tree of life room", "heart of the mountain", "core of the earth",
    "center of the sun room", "inside a giant crystal", "inside a bubble", "inside a clock",
    "inside a computer", "inside a brain", "inside a cell", "inside an atom",
    "inside a book", "inside a painting", "inside a photograph", "inside a memory",
    "inside a dream", "inside a thought", "inside a feeling", "inside a soul"
]

commercial_items = [
    "cyberpunk bar", "luxury hotel lobby", "abandoned mall", "space station corridor",
    "neon lit diner", "high-end restaurant", "busy coffee shop", "quiet bookstore",
    "massive department store", "boutique clothing shop", "antique store", "jewelry shop",
    "art gallery", "modern museum", "science center", "aquarium", "planetarium",
    "multiplex cinema", "retro theater", "concert hall", "opera house", "nightclub",
    "underground jazz club", "dive bar", "sports bar", "rooftop lounge", "casino floor",
    "arcade hall", "bowling alley", "indoor skating rink", "gymnasium", "yoga studio",
    "spa and wellness center", "hair salon", "barber shop", "tattoo parlor",
    "pet store", "veterinary clinic", "pharmacy", "medical clinic", "dental office",
    "law firm office", "architecture firm", "tech startup office", "corporate boardroom",
    "bank lobby", "stock exchange", "convention center hall", "hotel ballroom",
    "airport terminal", "train station hall", "subway platform", "bus station waiting room",
    "ferry terminal", "car dealership", "auto repair shop", "gas station shop",
    "convenience store", "supermarket", "farmers market stall", "bakery", "butcher shop",
    "florist", "hardware store", "electronics store", "camera shop", "music store",
    "toy store", "hobby shop", "stationary store", "gift shop", "duty free shop",
    "shopping arcade", "outdoor mall", "souk market", "bazaar", "food court",
    "ice cream parlor", "candy store", "chocolate shop", "wine shop", "liquor store",
    "cannabis dispensary", "vape shop", "tobacco shop", "smoke lounge", "hookah bar",
    "karaoke box", "internet cafe", "gaming lounge", "escape room lobby", "laser tag arena",
    "paintball field office", "indoor climbing gym", "trampoline park", "mini golf course",
    "bowling center", "billiard hall", "dart bar", "comedy club", "magic theater",
    "puppet theater", "street performer pitch", "pop-up shop", "flea market booth",
    "thrift store", "consignment shop", "pawn shop", "laundromat", "dry cleaners",
    "tailor shop", "shoe repair shop", "locksmith shop", "post office", "shipping center",
    "print shop", "co-working space", "meeting room", "private office", "cubicle farm",
    "call center", "data center aisle", "server room", "factory showroom", "industrial warehouse",
    "distribution center", "cold storage room", "brewery taproom", "distillery tasting room",
    "winery cellar", "cider house", "meadery", "juice bar", "smoothie shop", "bubble tea shop",
    "tea house", "cat cafe", "dog cafe", "reptile cafe", "owl cafe", "maid cafe", "butler cafe",
    "themed restaurant", "dinner theater", "medieval dinner hall", "pirate tavern",
    "speakeasy", "secret bar", "hidden club", "exclusive members lounge", "airport lounge",
    "first class cabin", "luxury train car", "cruise ship lounge", "casino vip room",
    "high rollers suite", "auction house", "art studio gallery", "design studio",
    "photography studio", "film studio set", "recording studio", "television studio",
    "radio station", "newsroom", "advertising agency", "marketing firm", "public relations office",
    "consulting firm", "financial services office", "insurance agency", "real estate office",
    "travel agency", "recruitment agency", "translation service office", "coworking hub",
    "innovation lab", "maker space", "hacker space", "incubator office", "accelerator hub",
    "venture capital office", "private equity firm", "hedge fund office", "trading floor",
    "central bank vault", "gold refinery", "diamond exchange", "commodity market",
    "shipping company office", "logistics hub", "freight terminal", "cargo port office",
    "customs office", "immigration center", "embassy reception", "consulate office",
    "government department", "tax office", "social security office", "post office lobby",
    "public library hall", "community center", "youth center", "senior center",
    "daycare center", "preschool classroom", "primary school hall", "high school corridor",
    "university lecture hall", "college library", "science lab", "language school",
    "music academy", "dance school", "art school studio", "drama school theater",
    "vocational training center", "driving school office", "flight school hangar",
    "nautical school", "culinary school kitchen", "fashion design studio", "beauty school",
    "massage school", "yoga teacher training", "meditation center", "retreat center lobby",
    "spiritual center", "temple hall", "church nave", "mosque prayer hall", "synagogue hall",
    "gurdwara", "monastery refectory", "convent parlor", "shrine interior", "pagoda hall",
    "cathedral", "basilica", "chapel", "funeral home", "crematorium lobby", "cemetery office",
    "morgue reception", "hospital lobby", "emergency room waiting", "doctor's waiting room",
    "dentist's waiting area", "physiotherapy clinic", "chiropractic office", "psychologist's office",
    "veterinary waiting room", "animal hospital", "wildlife rescue center", "zoo entrance",
    "safari park lobby", "botanical garden conservatory", "nature center", "visitor center",
    "national park office", "tourist information center", "travel kiosk", "currency exchange",
    "ticket office", "box office", "cloakroom", "concierge desk", "valet stand",
    "bellhop station", "laundry pickup", "room service kitchen", "hotel laundry",
    "commercial kitchen", "catering hall", "commissary kitchen", "food prep area",
    "dishwashing station", "walk-in freezer", "loading dock", "trash compactor area",
    "recycling station", "maintenance workshop", "security room", "cctv monitor room",
    "lost and found", "first aid station", "nursing room", "changing room", "fitting room",
    "public restroom", "restroom lounge", "janitor's closet", "electrical room", "mechanical room",
    "boiler room", "hvac control room", "elevator lobby", "stairwell", "corridor", "hallway",
    "fire exit", "roof access", "utility closet", "telecom room", "data closet",
    "sprinkler room", "pump room", "generator room", "fuel storage", "chemical storage",
    "hazardous waste area", "secure storage", "vault room", "strongroom", "panic room",
    "safe room", "bunker", "fallout shelter", "emergency center", "disaster relief hub",
    "charity office", "non-profit headquarters", "food bank warehouse", "clothing bank",
    "homeless shelter lobby", "refugee center", "animal shelter", "rescue mission",
    "halfway house", "rehab center lobby", "detox clinic", "blood bank", "organ donation center",
    "plasma center", "sperm bank", "fertility clinic", "maternity ward", "neonatal unit",
    "pediatric ward", "geriatric ward", "oncology center", "cardiology unit", "radiology room",
    "mri suite", "ct scan room", "x-ray lab", "medical lab", "pathology lab", "forensic lab",
    "police station lobby", "precinct house", "detective bureau", "evidence locker",
    "holding cell", "interrogation room", "booking area", "police motor pool",
    "fire station bay", "firefighter quarters", "paramedic station", "coast guard station",
    "search and rescue base", "military recruitment office", "military police office",
    "veterans affairs office", "unemployment office", "labor board office", "patent office",
    "copyright office", "trademark office", "standardization bureau", "quality control office",
    "environmental agency", "health inspector office", "building permit office", "zoning office",
    "urban planning department", "public works office", "sanitation department",
    "water department lobby", "electric company office", "gas company lobby",
    "telecom provider store", "mobile phone shop", "internet service provider office",
    "cable company office", "media conglomerate office", "publishing house", "magazine office",
    "newspaper building", "tv station lobby", "radio station booth", "recording studio hall",
    "film production office", "animation studio", "gaming company office", "software house",
    "ai research lab", "robotics company", "biotech firm", "pharmaceutical company",
    "medical device manufacturer", "aerospace company", "defense contractor", "private military company",
    "security firm office", "investigation agency", "detective agency", "intelligence agency",
    "spy agency lobby", "secret base entrance", "underground facility", "mountain base",
    "island base", "underwater station", "space station", "moon base", "mars colony",
    "asteroid mining station", "orbital platform", "satellite control room", "mission control",
    "launch control", "galactic trade hub", "interstellar port", "dimensional gateway station",
    "time travel agency", "reality management bureau", "fate control center", "destiny office",
    "superhero headquarters", "villain hideout lobby", "secret lair", "training facility",
    "danger room", "heroic hall", "justice league style hall", "avengers style tower lobby",
    "magic council hall", "wizard's guild", "adventurer's guild", "mercenary guild",
    "thieves' guild entrance", "assassin's guild lobby", "alchemist's society", "herbalist's guild",
    "craftsman's guild", "merchant's guild hall", "trade house", "chamber of commerce",
    "better business bureau", "consumer protection office", "fair trade office", "ethical standards bureau",
    "international trade organization", "world bank office", "imf office", "un headquarters lobby",
    "unesco office", "who office", "red cross headquarters", "amnesty international office",
    "greenpeace office", "wwf office", "doctors without borders office", "unicef office",
    "care international office", "oxfam office", "save the children office", "habitat for humanity",
    "goodwill office", "salvation army office", "united way office", "rotary club hall",
    "lions club", "elks lodge", "masonic lodge hall", "knights of columbus", "shriners club",
    "odd fellows hall", "grange hall", "vfw post", "american legion hall", "country club lobby",
    "yacht club", "golf club", "tennis club", "polo club", "equestrian center lobby",
    "hunt club", "fishing club", "garden club", "bridge club", "chess club", "gaming club",
    "social club", "gentleman's club lounge", "lady's club", "women's institute hall",
    "scout hut", "girl guide hall", "boy scout hall", "youth hostel lobby", "backpacker's hostel",
    "glamping reception", "campground office", "rv park lobby", "marina office", "boathouse",
    "sailing school", "diving center", "surf school", "ski school office", "mountain guide office",
    "safari lodge lobby", "eco resort", "wilderness lodge", "hunting lodge", "fishing lodge",
    "retreat center", "meditation hall", "yoga shala", "ashram", "monastery", "nunnery",
    "convent", "seminary", "bible college", "yeshiva", "madrasa", "dhamma center",
    "zen center", "taoist temple", "shinto shrine hall", "hindu temple hall", "sikh temple",
    "buddhist temple", "cathedral hall", "basilica floor", "orthodox church", "coptic church",
    "evangelical megachurch", "unitarian universalist hall", "quaker meeting house",
    "bahai house of worship", "scientology center", "cult compound", "commune",
    "intentional community", "cohousing common house", "eco village hub", "sustainable community",
    "smart city hub", "future city center", "cyberpunk mega structure", "dystopian city hall",
    "utopian plaza", "solarpunk greenhouse", "biopunk lab", "nanopunk factory",
    "clockpunk clocktower", "dieselpunk station", "atompunk diner", "raypunk bridge",
    "silkpunk palace", "woodpunk hall", "stonepunk cave hall", "ironpunk forge",
    "steampunk airship station", "cyberpunk netrunner den", "futuristic bar", "alien cantina"
]

historical_items = [
    "medieval throne room", "ancient library", "victorian study", "renaissance workshop",
    "ancient roman bathhouse", "greek temple interior", "egyptian tomb chamber", "viking longhouse",
    "medieval castle great hall", "feudal japanese dojo", "samurai lord's chamber", "shogun's audience hall",
    "imperial chinese throne room", "mayan temple inner sanctum", "aztec palace hall", "incan sun temple interior",
    "mesopotamian ziggurat chamber", "persian palace audience hall", "ottoman harem room", "mughal emperor's court",
    "victorian ballroom", "edwardian dining room", "regency drawing room", "baroque palace gallery",
    "rococo salon", "renaissance palazzo courtyard", "medieval cathedral nave", "gothic abbey library",
    "byzantine church interior", "early christian catacomb", "ancient babylonian garden house",
    "sumerian scribe's room", "ancient greek gymnasium", "roman senator's villa", "medieval monastery scriptorium",
    "crusader knight's armory", "templar secret chamber", "illuminati meeting hall", "freemason lodge interior",
    "victorian smoking room", "19th century apothecary", "colonial tavern interior", "pioneer log cabin interior",
    "wild west saloon", "gold rush era bank", "industrial revolution factory floor", "victorian workhouse hall",
    "edwardian servant's quarters", "renaissance artist's studio", "medieval alchemy lab", "ancient greek theater stage",
    "roman colosseum tunnels", "gladiator barracks", "medieval dungeon cell", "inquisition torture chamber",
    "renaissance map room", "victorian scientific laboratory", "edwardian smoking lounge", "1920s speakeasy",
    "1930s jazz club", "1940s war room", "1950s diner interior", "colonial governor's office",
    "ancient egyptian embalming room", "viking chieftain's hut", "medieval village forge", "renaissance merchant house",
    "victorian nursery", "edwardian conservatory", "regency library", "baroque opera house box",
    "rococo bedroom", "renaissance study", "medieval guard tower room", "ancient greek oracle chamber",
    "roman baths caldarium", "medieval feast hall", "renaissance chapel", "victorian parlor",
    "edwardian garden room", "colonial courthouse", "wild west jail", "19th century schoolhouse",
    "ancient persian library", "medieval cathedral crypt", "renaissance clocktower room", "victorian greenhouse",
    "edwardian ballroom", "1920s art deco lounge", "1930s cinema auditorium", "1940s bunker interior",
    "1950s soda fountain", "ancient roman bakery", "medieval mill interior", "renaissance counting house",
    "victorian sewing room", "edwardian butler's pantry", "colonial kitchen", "wild west general store",
    "19th century print shop", "ancient greek ceramic workshop", "roman mosaic studio", "medieval weaver's cottage",
    "renaissance goldsmith's shop", "victorian jewelry store", "edwardian millinery", "1920s fashion salon",
    "1930s department store", "1940s radio station booth", "1950s living room", "ancient egyptian granary",
    "viking shipbuilder's yard", "medieval stone mason's yard", "renaissance glassblower's furnace",
    "victorian ironworks", "edwardian steam engine room", "colonial shipyard office", "wild west post office",
    "19th century telegraph office", "ancient roman law court", "greek assembly hall", "medieval town council room",
    "renaissance diplomatic chamber", "victorian embassy", "edwardian social club", "1920s cabaret stage",
    "1930s grand hotel lobby", "1940s field hospital tent", "1950s bowling alley", "ancient egyptian papyrus workshop",
    "medieval manuscript library", "renaissance printing house", "victorian library stacks", "edwardian lecture hall",
    "colonial schoolroom", "wild west church", "19th century hospital ward", "ancient roman surgery",
    "greek healing temple", "medieval herbalist's shop", "renaissance apothecary", "victorian operating theater",
    "edwardian medical lab", "1920s psychic's parlor", "1930s newsroom", "1940s military barracks",
    "1950s fallout shelter", "ancient egyptian palace courtyard", "viking mead hall", "medieval castle armory",
    "renaissance palace terrace", "victorian roof garden", "edwardian hunting lodge", "colonial mansion library",
    "wild west ranch house", "19th century farmhouse kitchen", "ancient greek pottery workshop",
    "roman villas peristyle", "medieval abbey cloisters", "renaissance university hall", "victorian museum gallery",
    "edwardian department store", "1920s movie palace", "1930s travel agency", "1940s air raid shelter",
    "1950s suburban kitchen", "ancient roman wine shop", "medieval tavern cellar", "renaissance spice merchant shop",
    "victorian tea room", "edwardian coffee house", "colonial trading post", "wild west stagecoach station",
    "19th century train station lobby", "ancient egyptian pharaoh's bedroom", "viking burial mound interior",
    "medieval peasant's loft", "renaissance astronomer's tower", "victorian observatory", "edwardian yacht cabin",
    "colonial plantation house", "wild west sheriff's office", "19th century bank vault", "ancient roman market stall",
    "medieval bazaar alley", "renaissance canal house", "victorian tenement room", "edwardian tenement hallway",
    "1920s flapper's apartment", "1930s radio studio", "1940s darkroom", "1950s garage workshop",
    "ancient egyptian jewelers", "viking weapon forge", "medieval blacksmith shop", "renaissance armorer's shop",
    "victorian watchmaker's bench", "edwardian tailor shop", "colonial shoemaker's bench", "wild west gunsmith shop",
    "19th century leather tannery", "ancient roman laundry", "medieval dye works", "renaissance parchment maker",
    "victorian candle factory", "edwardian soap factory", "1920s distillery", "1930s brewery",
    "1940s munitions factory", "1950s car factory", "ancient egyptian quarry office", "viking lumber yard",
    "medieval carpenter shop", "renaissance sculptor's studio", "victorian stone carver shop", "edwardian architect's office",
    "colonial land surveyor office", "wild west land claim office", "19th century patent office",
    "ancient roman tax office", "medieval scribe's desk", "renaissance bank teller window", "victorian stockbroker office",
    "edwardian accountant's office", "1920s legal office", "1930s insurance office", "1940s codebreaking room",
    "1950s advertising agency", "ancient egyptian priest's quarters", "viking seer's hut", "medieval monk's cell",
    "renaissance cardinal's office", "victorian vicarage study", "edwardian parsonage parlor", "colonial meeting house",
    "wild west mission chapel", "19th century revival tent", "ancient roman shrine", "greek temple treasury",
    "medieval abbey refectory", "renaissance catacomb entrance", "victorian crypt", "edwardian mausoleum",
    "1920s funeral parlor", "1930s morgue", "1940s military cemetery office", "1950s memorial hall",
    "ancient egyptian river boat cabin", "viking longship deck", "medieval galley interior", "renaissance caravel cabin",
    "victorian steamship lounge", "edwardian ocean liner suite", "colonial clipper ship cabin", "wild west train car",
    "19th century stagecoach interior", "1920s luxury car interior", "1930s airplane cabin", "1940s jeep interior",
    "1950s station wagon interior", "ancient roman inn", "medieval waypoint house", "renaissance coaching inn",
    "victorian hotel suite", "edwardian grand hotel", "colonial lodging house", "wild west boarding house",
    "19th century flophouse", "1920s youth hostel", "1930s motor court room", "1940s transit hotel",
    "1950s roadside motel", "ancient greek agora market", "roman forum arcade", "medieval street market",
    "renaissance trade fair hall", "victorian covered market", "edwardian arcade", "1920s department store floor",
    "1930s supermarket", "1940s ration shop", "1950s shopping mall", "ancient egyptian temple pylons",
    "viking fort gatehouse", "medieval castle walls interior", "renaissance bastion room", "victorian fort barracks",
    "edwardian naval base office", "colonial fort magazine", "wild west cavalry fort", "19th century armory hall",
    "1920s military headquarters", "1930s civil defense office", "1940s resistance hideout", "1950s command bunker",
    "ancient greek senate", "roman curia", "medieval parliament hall", "renaissance council of ten chamber",
    "victorian house of commons", "edwardian house of lords", "colonial assembly room", "wild west town hall",
    "19th century mayor's office", "1920s government press room", "1930s ministry office", "1940s intelligence bureau",
    "1950s state department lobby", "ancient egyptian court of justice", "greek law court", "medieval assize court",
    "renaissance star chamber", "victorian courtroom", "edwardian judge's chambers", "colonial magistrate office",
    "wild west circuit court", "19th century supreme court hall", "1920s probation office", "1930s juvenile court",
    "1940s military tribunal room", "1950s police court", "ancient roman prison", "medieval oubliette",
    "renaissance prison tower", "victorian gaol cell", "edwardian convict ship cabin", "colonial stocks and pillory",
    "wild west gallows platform", "19th century executioner's room", "1920s electric chair room", "1930s gas chamber",
    "1940s prisoner of war camp", "1950s maximum security cell", "ancient greek artist's studio",
    "roman sculptor workshop", "medieval illuminated manuscript room", "renaissance tapestry workshop",
    "victorian pottery works", "edwardian furniture maker", "colonial blacksmith's house", "wild west saddlemaker shop",
    "19th century watchmaker shop", "1920s auto mechanic shop", "1930s electronics repair shop",
    "1940s airplane hangar", "1950s television repair shop", "ancient egyptian weavers", "viking spinners",
    "medieval wool hall", "renaissance silk merchant", "victorian textile mill", "edwardian clothing store",
    "colonial mercer's shop", "wild west haberdashery", "19th century dry goods store", "1920s boutique",
    "1930s thrift store", "1940s army surplus store", "1950s hardware store", "ancient roman butcher",
    "medieval fishmonger", "renaissance fruiterer", "victorian greengrocer", "edwardian dairy",
    "colonial cooper's shop", "wild west wheelwright", "19th century farrier", "1920s barber shop",
    "1930s hair salon", "1940s beauty parlor", "1950s laundromat", "ancient greek pharmacy",
    "roman medicine shop", "medieval apothecary's garden", "renaissance physician's study",
    "victorian chemist", "edwardian optician", "colonial dentist", "wild west doctor's buggy",
    "19th century asylum ward", "1920s sanitarium lounge", "1930s mental hospital", "1940s burn unit",
    "1950s polio ward", "ancient egyptian school", "greek academy", "roman schoolroom",
    "medieval parish school", "renaissance college hall", "victorian primary school", "edwardian boarding school",
    "colonial village school", "wild west one room schoolhouse", "19th century industrial school",
    "1920s university laboratory", "1930s research institute", "1940s training center", "1950s high school gym",
    "ancient roman library", "greek pergamon library", "medieval cathedral library", "renaissance princely library",
    "victorian public library", "edwardian reading room", "colonial lending library", "wild west town library",
    "19th century scholarly library", "1920s private collection room", "1930s microfilm room", "1940s war archive",
    "1950s periodical room", "ancient egyptian astronomers", "greek mathematicians", "roman engineers",
    "medieval navigators", "renaissance explorers", "victorian naturalists", "edwardian geologists",
    "colonial botanists", "wild west scouts", "19th century inventors", "1920s aviators",
    "1930s archaeologists", "1940s physicists", "1950s rocket scientists"
]

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

def update_section(lines, parent, child, new_items):
    parent_idx = -1
    for i, line in enumerate(lines):
        if line.strip() == f"{parent}:":
            parent_idx = i
            break
    
    if parent_idx == -1: return lines
    
    child_idx = -1
    for i in range(parent_idx + 1, len(lines)):
        if line.strip() == f"{child}:":
            child_idx = i
            break
        if lines[i].strip() and not lines[i].startswith('  ') and ':' in lines[i]:
            break
            
    # Search for child within the parent's scope
    for i in range(parent_idx + 1, len(lines)):
        if lines[i].strip() == f"{child}:":
            child_idx = i
            break
        if lines[i].strip() and not lines[i].startswith('  ') and ':' in lines[i]:
             break

    if child_idx == -1: return lines
    
    # Find the end of this child section
    end_idx = child_idx + 1
    while end_idx < len(lines):
        if lines[end_idx].strip() and not lines[end_idx].startswith('    ') and ':' in lines[end_idx]:
            break
        if lines[end_idx].strip() and not lines[end_idx].strip().startswith('-') and ':' in lines[end_idx].strip():
             break
        end_idx += 1
    
    # Replace contents
    formatted = [f"    - {item}\n" for item in new_items]
    lines[child_idx+1:end_idx] = formatted
    return lines

lines = update_section(lines, "indoor", "residential", residential_items)
lines = update_section(lines, "indoor", "commercial", commercial_items)
lines = update_section(lines, "indoor", "historical", historical_items)

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Expanded indoor sections.")
